import type { Metadata } from "next";
import "./globals.css";
import { Header } from "./componets/Header";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`antialiased min-h-screen flex flex-col`}
            >
                <Header />
                {children}
            </body>
        </html>
    );
}
